import type { DocumentDetail } from "@/lib/domain/types";
import { toOutputViewModel } from "./output-view-model";
export const safeFilename = (title: string) => (title.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "pricing-document").slice(0, 80);
const esc = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;");
export function htmlForDocument(document: DocumentDetail) {
  const output = toOutputViewModel(document);
  const rows = output.lineItems.map((line) => `<tr><td>${esc(line.description)}</td><td class="num">${esc(line.quantity)}</td><td class="num">$${esc(line.unitPrice)}</td><td>${esc(line.discount)}</td><td class="num">$${esc(line.lineTotal)}</td></tr>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(output.title)}</title><style>body{font:14px system-ui,sans-serif;color:#18201c;max-width:820px;margin:48px auto;padding:0 24px}header{display:flex;justify-content:space-between;border-bottom:2px solid #18201c;padding-bottom:20px}h1{font-size:30px;margin:0}.meta{text-align:right;color:#69736d;line-height:1.7}table{width:100%;border-collapse:collapse;margin-top:30px}th{text-align:left;border-bottom:1px solid #18201c;padding:8px 5px;font-size:11px;text-transform:uppercase}td{padding:10px 5px;border-bottom:1px solid #dfe4df}.num{text-align:right;font-variant-numeric:tabular-nums}.totals{width:280px;margin:22px 0 0 auto}.totals div{display:flex;justify-content:space-between;padding:6px 0}.grand{border-top:2px solid #18201c;font-weight:700;font-size:17px}</style></head><body><header><div><h1>${esc(output.title)}</h1><p>${esc(output.statusLabel)}</p></div><div class="meta">${esc(output.customer)}<br>Issue date: ${esc(output.issueDate)}</div></header><table><thead><tr><th>Description</th><th class="num">Qty</th><th class="num">Unit price</th><th>Discount</th><th class="num">Line total</th></tr></thead><tbody>${rows}</tbody></table><div class="totals"><div><span>Subtotal</span><strong>$${output.subtotal}</strong></div><div><span>Discount</span><strong>−$${output.totalDiscount}</strong></div><div><span>Tax</span><strong>$${output.totalTax}</strong></div><div class="grand"><span>Total</span><strong>$${output.grandTotal}</strong></div></div></body></html>`;
}
